version: "3.8"
services: 
  golang_webapp:
    container_name: webapp
    image: sivaramsk/webapp:0.7
    ports:
      - "5000:5000"
    restart: always

  nginx:
    container_name: productions_nginx
    image: nginx:alpine
    volumes:
      - type: bind
        source: ./default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: bind
        source: ./cert/blueforge_in.key
        target: /etc/nginx/cert/blueforge_in.key
        read_only: true
      - type: bind
        source: ./cert/blueforge_in.crt
        target: /etc/nginx/cert/blueforge_in.crt
        read_only: true
      - type: bind
        source: ./cert/dhparam.pem
        target: /etc/nginx/cert/dhparam.pem
        read_only: true
      - type: bind
        source: ./index.html
        target: /var/www/localhost/htdocs/index.html
    ports:
      - 8080:8080
      - 8443:8443
